### ISSUE TITLE
How to get `home.html` template to render some particular page?

### ISSUE THREAD

**Issue by metasoarous** [cryogen-project/cryogen#112]
I'm specifically trying to get either an `about.md` or `index.md` page to render there, but am having trouble figuring out how. The shape of the data available to the templates is rather opaque to me, and I would like to understand that better how I'd render this page, but haven't found anything in the docs that would lead me in the right direction here. I'm sure this is just a simple thing, but seems like something folks would commonly want to do.

**Comment by lacarmen** [comment]
Well if you want to render a page using the `home.html` template then you can just specify `:layout :home` in the metadata of your Markdown file but I don't think this is what you want :)

I suspect you want to display the contents of an `about.md` file as the index of your site? You can do this by changing the [`compile-index`](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L331) function in the compiler so that the data includes the page content that you want.
