### ISSUE TITLE
Feature request: Basic Search

### ISSUE THREAD

**Issue by msszczep** [cryogen-project/cryogen#115]
It would be nice to have a basic search tool for Cryogen.  I have more than 450 pages on my Cryogen site, and it's a lot to have to sift through.  Some basic search functionality for content in the posts directory would be nice.

**Comment by lacarmen** [comment]
What would you like to be able to search through? Post content and post titles?

**Comment by msszczep** [comment]
I would like to search through the content and titles of both posts and pages.  Thanks!

**Comment by emidln** [comment]
I'm starting to use this more too, and I think we could do a basic search pretty easily via something like this: https://github.com/olivernn/lunr.js. I found that while scanning on the cljsjs packages.

An alternative might provide a form for a Google custom search or Duck Duck Go custom search.

**Comment by tjungbauer** [comment]
I have added it to my cryogen page during this commit: https://github.com/stderrat/blog-src/commit/5d86ec3253bf9afc0cafed0659770add2c473867 (demo at https://blog.stderr.at)

using slightly modified javascripts from here: https://github.com/BLE-LTER/Lunr-Index-and-Search-for-Static-Sites

basically it is a small change in the html files, moreover one script builds the actual lunrjs index, which is then used to find the results. 

I am not sure if I should put everything into a pull request, since this issue started 2016. If you want it please let me know, or otherwise, if something finds above usefull feel free to copy :)

**Comment by lacarmen** [comment]
@tjungbauer That looks really nice! If you're up for it, I think "implementing" this as a new page under "Additional Resources" in the [docs](http://cryogenweb.org/docs/home.html).

**Comment by tjungbauer** [comment]
@lacarmen sure thing. What exactly will you need form me? Will you just dd it to the docs, or shall I document it?

**Comment by lacarmen** [comment]
@tjungbauer Can you add a new page to the [cryogen-docs](https://github.com/cryogen-project/cryogen-docs/tree/master/resources/templates/md/docs)? You can make a new folder in [templates](https://github.com/cryogen-project/cryogen-docs/tree/master/resources/templates) for the js files then add it to the [resources to be copied](https://github.com/cryogen-project/cryogen-docs/blob/master/resources/templates/config.edn#L15) and then probably just link them from the page.

**Comment by tjungbauer** [comment]
@lacarmen very well, you should see a pull request now :) 
many thanks.

**Comment by lacarmen** [comment]
@tjungbauer Thank YOU! 🎉

**Comment by holyjak** [comment]
http://cryogenweb.org/docs/add-basic-search.html explains how to do this so I guess we can close this issues.
