### ISSUE TITLE
Question: is it possible to have a blog in two languages?

### ISSUE THREAD

**Issue by daplay** [cryogen-project/cryogen#116]

**Comment by lacarmen** [comment]
Can you give me some more details? It's certainly possible but there's different ways of achieving that.

**Comment by daplay** [comment]
I was thinking on adding two keys to config.edn like languages and default language (maybe all these we could be put it a single map in config.edn) and then use that to expose an object in Selmer context with the available languages for a particular page (if any)

**Comment by lacarmen** [comment]
Okay the answer is no, there's no mechanism that does what you're suggesting right now but I can suggest a different way to create a blog in two languages. (The cryogen documentation site had both English and German docs before but I stopped supporting the German version.)

So what you can do is create two cryogen projects - one for your default language, and one for the other language. Give the two projects different `blog-prefix`'s like `"/en"` and `"/jp"` for example. When you deploy your site you'll have to move the folders around but that could be done with a script.

If you could clarify your idea further then I think it could make a good plugin. I'm hesitant to add this as a feature to the default compiler since I can't see very many people using it.
