### ISSUE TITLE
Ordering multiple posts on the same day?

### ISSUE THREAD

**Issue by yatesco** [cryogen-project/cryogen#126]
Hi,

Loving this :-). I noticed however, that if I edit multiple posts on the same day it doesn't follow the correct order, which isn't surprising as the configuration only discusses setting the date format, not the time format.

Is it possible add a timestamp as well, or is there another way to dictate the ordering for multiple posts on the same day?

Thanks!

**Comment by lacarmen** [comment]
It works with a timestamp if you update the `:post-date-format` field in the config to reflect that but the caveat is that you'd have to specify your datetime within the metadata in your md/asc files rather than the filenames because the compiler is currently hardcoded to look at the first 10 characters in the filenames for a date.

So you could have this in your `config.edn`
```
 :post-date-format   "yyyy-MM-dd HH:mm"
```

And then each post would have to contain something like
```
:date "2016-09-29 12:00" 
```

There could be better support around this but usually people aren't writing more than one post in a day so it hasn't come up until now. :)

**Comment by yatesco** [comment]
That's great - thanks Carmen. I always feel bad right about now because
I should send in a PR but timescales and real-life get in the way :-(.

On Fri, 30 Sep 2016, at 04:52 AM, Carmen La wrote:
> It works with a timestamp if you update the :post-date-format field in
> the config to reflect that but the caveat is that you'd have to
> specify your datetime within the metadata in your md/asc files rather
> than the filenames because the compiler is currently hardcoded to look
> at the first 10 characters in the filenames for a date.
> So you could have this in your config.edn


>  :post-date-format   "yyyy-MM-dd HH:mm"
>
> And then each post would have to contain something like


> :date "2016-09-29 12:00"
>
> There could be better support around this but usually people aren't
> writing more than one post in a day so it hasn't come up until now. :)
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/cryogen-project/cryogen/issues/126#issuecomment-250652545

**Comment by lacarmen** [comment]
Closing this as the workaround should suffice since this doesn't seem to be a common use case. A new issue can be opened if further enhancements to the project are needed.
