### ISSUE TITLE
Expose selmer's add-filter! and add-tag! fns for more extensible templating.

### ISSUE THREAD

**Issue by SVMBrown** [cryogen-project/cryogen#132]
It would be useful to be able to write new filters and tags for templating.

**Comment by emidln** [comment]
We can already do this pretty easily. I created a file called `selmer.clj`:

https://github.com/ddftwiki/ssg/blob/master/src/cryogen/selmer.clj

Then I just needed to require this in the generated `crygogen.core`:

https://github.com/ddftwiki/ssg/blob/master/src/cryogen/core.clj#L4

And for it to be picked up by ring, I also included `cryogen.core` in `crygoen.server`:

https://github.com/ddftwiki/ssg/blob/master/src/cryogen/server.clj#L10

**Comment by lacarmen** [comment]
@emidln If you'd like to create a PR that would be great.

**Comment by emidln** [comment]
There is no PR to create really. The only thing in there that seems possibly PR worthy would be requiring `crygogen.core` from `cryogen.server` so that there is a single point to require additional functionality `cryogen.core`. The rest is just normal extension. Unless you mean creating an empty namespace to add selmer stuff by default?

**Comment by yogthos** [comment]
I agree that adding an example of creating custom tags and filters to the docs is the way to go.

**Comment by lacarmen** [comment]
Ah I see, I'll make a new issue over on the cryogen-docs repo.

**Comment by lacarmen** [comment]
Closing this in favour of the cryogen-docs issue.
