### ISSUE TITLE
Seperate lines being squashed.

### ISSUE THREAD

**Issue by rjb25** [cryogen-project/cryogen#141]
If I have two sentences in a mardown file like so:
hey how are you?
Good How about you?
It translates to:
hey how are you?Good How about you?
Is this intentional? Why ignore line breaks? And if you are going to ignore them at least put a space between line content.
I think this might mean that you are not translating the files line breaks to lines breaks in markdown-clj?
This boils down to 
1. Make it so that new lines in files are translated to spaces.
***OR***
2. Make new lines be recognized as new lines.

**Comment by lacarmen** [comment]
That is indeed intentional. It's how markdown syntax works. To get a line break in the output you need to end your line with two spaces and a line break like so:

```
Hello<space><space>
There
```

If you want to start a new paragraph then you need to end your line with two line breaks like so:

```
Hello

There
```

Paragraph and line break syntax is documented [here](https://daringfireball.net/projects/markdown/syntax#p). Additionally, markdown-clj has a live demo site [here](https://rawgit.com/yogthos/markdown-clj/master/demo/markdown.html).

**Comment by rjb25** [comment]
The above answers one of the two issues, thanks. I now know that if I want line breaks I need to have two spaces at the end. There is still the issue of no space being translated from the new line.
Take this example text:
```
Hello
World
```
In this markdown-clj [emulator](https://rawgit.com/yogthos/markdown-clj/master/demo/markdown.html)
it translates to `Hello World`
However when I do the same thing in a markdown file for my cryogen blog I get `HelloWorld` with no space. Is this also intentional?

**Comment by lacarmen** [comment]
I'm not sure about that one. Cryogen doesn't do anything special with the spaces/newlines as far as I can tell from a quick glance. Maybe try using the new [cryogen-flexmark](https://github.com/cryogen-project/cryogen-flexmark) @yogthos added. I can take a closer look at the issue in the meantime.

**Comment by rjb25** [comment]
Thanks, I'll take a look at that.

**Comment by rjb25** [comment]
This issue is being discussed further [here](https://github.com/yogthos/markdown-clj/issues/119)
