### ISSUE TITLE
is cryogen suited to use in github pages?

### ISSUE THREAD

**Issue by tangrammer** [cryogen-project/cryogen#36]
Hi cryogen guys,
I'm trying to use cryogen in github pages but it's being really complicated,...
Is there some preferred or suited way to do that?

thanks!
Juan

**Comment by dl1ely** [comment]
@tangrammer I am answering a bit late, but `:keep-files` was added for that exact reason: Deploying to github pages without having to copy over the generated files to a separate git repo. But i see you selected a different approach in your blog post. There seem to be many ways :smile:

**Comment by tangrammer** [comment]
@dl1ely Thanks!, could you specify the exact flow to keep your blog in github and your webapp working?
I'll try to get it working with :keep-files but I couldn't ...

**Comment by dl1ely** [comment]
Hi,

for me it felt straightforward. I let Cryogen create the static files, then i used `git init` in `resources/public` and added all files and committed them. Then i connected that repo with the github-repo for dl1ely.github.io (using `git add remote …`) and pushed to remote. Now the `public` folder was online via github.io. Before recreating the files in `resources/public`, i added `:keep-files ['.git']` to `config.edn` to protect the git metadata for the `resources` directory (But you can to this step at first, if you wish). Then i added a post and let cryogen recreate the static files. `.git` will not get deleted, so `git status` only shows the differences between the new created files and the previously committed version, despite that ALL files have been recreated. I commit the changed and new files and push to the remote repo. New/Changed files are online.

So, instead of copying over generated files to another directory that is versioned by git, i directly use the `resources` directory of cryogen and keep the `.git' directory there.

**Comment by tangrammer** [comment]
@dl1ely But in this case, how do you keep tracked your new .md files that probably you are working on but yet they aren't ready to be published?

**Comment by dl1ely** [comment]
@tangrammer I version the cryogen directory separately and .gitignore the
resources dir

tangrammer <notifications@github.com> schrieb am Mo., 19. Jan. 2015 22:28:

**Comment by tangrammer** [comment]
Stefan, could you specify this last part and full github flow for future
users?
Then, we could compare with my trick, I think it will help a lot!
Thanks

2015-01-20 6:06 GMT+00:00 Stefan Pfeiffer <notifications@github.com>:

**Comment by dl1ely** [comment]
I will try as soon as my time allows…

tangrammer <notifications@github.com> schrieb am Di., 20. Jan. 2015 09:01:

**Comment by dl1ely** [comment]
I am very late on this one, but i wanted to deliver:
http://dl1ely.github.io/posts/2015-03-04-how-to-use-cryogen-with-github-pages.html

Sorry.

**Comment by yatesco** [comment]
hi @dl1ely - just a note to say the URL points to a 404 on GitHub Pages. Irony abounds :-).

**Comment by dl1ely** [comment]
@yatesco You are right. The internet is a volatile medium. A abandoned cryogen some time ago for hubpress, moved over some posts by hand (but not all, especially not the cryogen ones), and the URLs are different. Sorry for that.

**Comment by DerHowie** [comment]
> @dl1ely But in this case, how do you keep tracked your new .md files that probably you are working on but yet they aren't ready to be published?

I ran into this issue while trying to publish my blog to github using cryogen. dl1ely's explanation is no longer available, but I figured out a pretty simple solution to the question posed above and thought I would share it in case anyone else stumbles upon this as I did.

In `config.edn` you can specific `:ignored-files`. If you just come up with a naming convention for markdown files that aren't ready to be published, you can ignore your work-in-progress files using a regex.

By adding `#"[\-\w\d]+(wip\.md)"` to the `:ignored-files`, for example, I can name a post `2017-01-03-wip.md` and it will not be added to cryogen's generated files if I need to make an update to an existing file and commit it to github. (any file in this case ending with wip.md will not be added to generated files)

**Comment by lacarmen** [comment]
You can add a `:draft?` key to your post metadata and set it to `true` to flag a post as a draft. It won't be included in the compilation process. ([Docs here](http://cryogenweb.org/docs/writing-posts.html))

Alternatively, a PR was recently submitted and it enables you to set a `:hide-future-posts?` key to `true` in the `config.edn` to have only current and past posts be included in the compilation process. ([Docs here](http://cryogenweb.org/docs/configuration.html))

**Comment by DerHowie** [comment]
@lacarmen that's much more straight-forward. Thanks for the reply. I should read the docs more carefully before interjecting!
