### ISSUE TITLE
Markdown support for links-at-bottom?

### ISSUE THREAD

**Issue by eraserhd** [cryogen-project/cryogen#39]
Is it a good idea to have a selection of markdown engine?  Or is there an option to markdown-clj to enable this?  

``` markdown
Go [here] to do such-and-such.

[here]: http://example.com/
```

**Comment by LocusOfCtrl** [comment]
Bringing up this old issue from the dead :) The "reference-style links" feature was added to `markdown-clj` a while back but is not enabled by default (unless one passes `:reference-links? true` to `md-to-html-string`). Would it be possible to have a way to specify Markdown processor options in `config.edn` -- or is there already another way to do this that I'm not aware of?

**Comment by lacarmen** [comment]
@LocusOfCtrl  Reference style links should already be enabled https://github.com/cryogen-project/cryogen-markdown/blob/master/src/cryogen_markdown/core.clj#L27 Is it not working for you? 

Being able to specify Markdown processor options in the config.edn would be convenient but because the markup processor in Cryogen is swappable I'm less inclined to add that functionality.

**Comment by LocusOfCtrl** [comment]
> Reference style links should already be enabled

Nevermind, they are! I misunderstood what these links are. Just tested and it works!
