### ISSUE TITLE
Where to place static top-level files?

### ISSUE THREAD

**Issue by MicahElliott** [cryogen-project/cryogen#66]
There are a handful of files that I'd like to live at the top level of the blog (or they could be in some dir): favicon.png, my-gpg-key.asc, robots.txt, etc. Where should these be placed? It seems that placing them in `resources/public/` does not work since they are destroyed on compile. I also tried placing them in the theme, but that felt odd and did not work either.

It seems the fix is to just copy files sitting at the top level into `public/`, in the same manner that is done with `404.html`.

**Comment by lacarmen** [comment]
You can place them in `resources/public/` if you'd like and add the names of your resources to the `:keep-files` vector in `config.edn` so that they don't get wiped out. 

Alternatively, you can place them under `resources/templates/` and add the names of your resources to the `:resources` vector in the `config.edn`

**Comment by MicahElliott** [comment]
Thanks Carmen! That `:keep-files` trick works great. Sorry I missed it in the docs. And thanks for all your efforts on this great project.
