### ISSUE TITLE
Feature request: Add support for Google analytics

### ISSUE THREAD

**Issue by markokocic** [cryogen-project/cryogen#81]
It would be good if cryogen could support optionally Google analytics, where user would put tracking code in `config.edn`, and have analytics automagically enabled on all of the pages.

**Comment by lacarmen** [comment]
With the way the compiler works, anything that you put into `config.edn` should be available to you in your selmer html templates.

https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L374 

The entire config map along with what's being merged with it always gets passed into the entire rendering function for a page. [Example here ](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L206)

So just add another key to your `config.edn` like `:analytics-script` and you can add {{analytics-script}} to your `base.html` file to inject your analytics script.

**Comment by markokocic** [comment]
Sure, it is fairly easy to add in a different ways, even hardcoding it in `base.html` template. I was just thinking if it is common enough to have "native" support, similar to disqus.

**Comment by lacarmen** [comment]
I suppose the disqus integration could be hardcoded as well but the reason why it has "native" support is because disqus components appear in both the blog post itself (the list of comments itself) and on the homepage as a link to the post's comments. 

Because google analytics just needs to be inserted into the base template, I don't think it's worth having "native" support for it.

**Comment by markokocic** [comment]
It makes sense if looked that way.
