### ISSUE TITLE
[feature request] google analytics support (solved if i add docs :-))

### ISSUE THREAD

**Issue by chadhs** [cryogen-project/cryogen#88]
i could add a doc / howto for this as follows (assign to me if it looks good to you):

add this to your config.edn file:

```
:google-analytics   "UA-#######-#"
```

create an `html/analytics.html` template that looks like this:

```
{% if google-analytics %}
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
    var pageTracker = _gat._getTracker("{{google-analytics}}");
pageTracker._trackPageview();
} catch(err) {}
</script>
{% endif %}
```

add this to the bottom of your `html/base.html` template:

```
{% include "/html/analytics.html" %}
```

**Comment by lacarmen** [comment]
I think most users just add the script straight into their `base.html` but if this could be useful for users users who would like to add analytics tracking to certain pages of their website rather than the entire site. 

So instead of adding `{% include "/html/analytics.html" %}` to the bottom of their `base.html` they would just add it to whatever pages they want tracking for.

**Comment by chadhs** [comment]
yeah that's a good point, it's easy to just put it in base or any template page.  i do love having the flexibility of adding additional keywords to config.edn so I can do this for my own organizational hangups haha!
