### ISSUE TITLE
[feature request: "clean urls"]

### ISSUE THREAD

**Issue by chadhs** [cryogen-project/cryogen#89]
idea:

in `config.en`

```
clean-urls:  yes
```

somewhere in the function(s) that handle output for pages & posts

`/pages/pagename.html` is instead `/pages/pagename/index.html`

resulting links would then become `/pages/pagename/`

PS: my intent with any of these feature requests is to get feedback, and then work on implementation. :-)

**Comment by lacarmen** [comment]
Sounds like a good idea :)

**Comment by chadhs** [comment]
cool, i'll make some time to try and figure this out.  =)

**Comment by jdhorwitz** [comment]
I can help with this if you need any.

**Comment by lacarmen** [comment]
Sounds good!

**Comment by jdhorwitz** [comment]
Thanks! I'm relatively new to Clojure, but not to programming.  I want to help out anyway I can.

**Comment by cqsd** [comment]
Is this being developed? I have some questions and can PR this issue once they're answered if you're not working on it atm @jdhorwitz @lacarmen

**Comment by lacarmen** [comment]
Not sure if @jdhorwitz has been working on this one but I haven't been. 

You can go ahead and ask your questions though :)

**Comment by cqsd** [comment]
My questions actually coalesced into one: how do you feel about putting URI generation into a generic `uri` function? My argument for it is that implementing the feature as described in the issue requires some logic _somewhere_, and I see two obvious places to put it:

1. Logic at write. Given, e.g., a URI `blog/pages/page.html` write out instead `blog/pages/page/index.html`. <strike>This changes the least code but</strike> Actually this is just terrible. Means more work to get proper links in the emitted HTML because the URI that gets passed around in the page map links to a nonexistent location.
2. Logic at URI generation + create new directories as necessary at write (e.g. writing `blog/pages/page/index.html` requires making a new dir `blog/pages/page`).

Under the second approach, I'd refactor most† URI creation into a `uri` function that looks something like this:
```
(defn uri 
  [file-name uri-type config]
  ...)
```
which, for example, makes these replacements
```
    (page-uri file-name config markup)
--> (uri file-name :page-root-uri config)
```
```
    (path "/" blog-prefix tag-root-uri (str (name tag) ".html")
--> (uri (str (name tag) ".html") :tag-root-uri config)
````

† It's just not necessary for some things like `blog/index.html`

**Comment by chadhs** [comment]
apologies for not making time to work on this; let me know if I can be of help @cqsd @lacarmen @jdhorwitz

**Comment by lacarmen** [comment]
@cqsd you're right, the second option is much better :)

**Comment by cqsd** [comment]
@chadhs If you're interested, I have this mostly done modulo a few small things (see [commits](https://github.com/cqsd/cryogen-core/commits/clean-urls)). I'm mostly concerned about adding complexity. Otherwise, I can finish this up later today.

Also, Cryogen's little development server will need a slight change, since right now it doesn't serve `index.html` from subfolders, but that's a different matter.

**Comment by chadhs** [comment]
@cqsd nice work and thank you! 😎👍🏼🚀
